[package]
name = "nrldpc-rs"
version = "0.1.0"
edition = "2018"

[lib]
name = "nrldpc"
path = "src/lib.rs"

[[example]]
name = "phy-rt"

[dependencies]
crc-any = "2.4.1"
ndarray = "0.15.4"
libm = "0.2.1"
num-traits = "0.2.14"
